### ISSUE TITLE
Error with bottom dates on report

### ISSUE THREAD

**Issue by juanpex** [fjyaniez/PortMonitor#1]
s 05/01/2013 1:16 AM and when the graphics go earlier the date dont change. At bottom shows:

05/01/13 01:10
05/01/13 01:00
05/01/13 00:50
etc, etc, etc
05/01/13 00:20
05/01/13 00:10
05/01/13 00:00
05/01/13 23:50 << SAME DATE
05/01/13 23:40 << SAME DATE

The valid date must be like this

05/01/13 00:10
05/01/13 00:00
04/01/13 23:50 << YESTERDAY
0401/13 23:40 << YESTERDAY

**Comment by fjyaniez** [comment]
23:50 refers to 00:50 (using 24 hours time format).

So (23:50) 00:50 still refers to 05/01/13.

**Comment by fjyaniez** [comment]
Anyway, could you please post a screenshot to confirm it?

**Comment by fjyaniez** [comment]
Closing.
