### ISSUE TITLE
Question: How long does an auth_token last?

### ISSUE THREAD

**Issue by Wouter0100** [fjyaniez/PortMonitor#10]
For how long will I be able to use an single auth_token? So, I login once through the API, and then use the auth_token in my code everywhere and it will work how long? This because hardcoding my password in my source isn't my favorite... Plus, more requests if I have to auth every page load (If I'm not caching anything).

Or: Is there a alternative way for this? Maybe a "app_token" which is account specific and then you don't need to auth? On this way you should also be able to regenerate the app_token when it's in "bad hands"..

**Comment by fjyaniez** [comment]
Every time a login request is performed, the auth_token is reset. The app_token is fixed by application though.

More info:
https://www.port-monitor.com/developers/api-reference#create_your_app
