### ISSUE TITLE
Bug: Date filtered response without target_ids

### ISSUE THREAD

**Issue by Wouter0100** [fjyaniez/PortMonitor#11]
I'm not 100% sure if this is a bug, but when I'm filtering the uptime or response times using date_range[from] and date_range[to] but without the target_ids within the reports category, I'm always receiving an empty response.. (I'd like to receive all my monitor's uptime within a day)

I know there are some workarounds for this, I will use those when this isn't a bug :-).

**Comment by fjyaniez** [comment]
Hi! It's the intended behavior, some people have so many monitors that displaying all the data by default is an expensive task.

However, having a group selected in the Dashboard, you can go to the uptime/reponse times tabs with all the group's monitors selected by default.
