### ISSUE TITLE
Chart axis shows 00:00 as 24:00

### ISSUE THREAD

**Issue by hho** [fjyaniez/PortMonitor#12]
In an uptime chart, the time axis shows 24:00 instead of 00:00 for the start of the day:

![image](https://cloud.githubusercontent.com/assets/478228/8507479/6223d326-2245-11e5-8e7e-8caa799862ea.png)

(it also uses American date format, even though the country is set to "Germany" in my profile)

**Comment by fjyaniez** [comment]
Hi @hho, using 24:00 instead of 00:00 is not common but acceptable in some cases like this one:

https://en.wikipedia.org/wiki/24-hour_clock#Midnight_00:00_and_24:00

Regarding the date format, will be supported in the future. 

Kind regards,

**Comment by hho** [comment]
Thanks for the schooling, but you missed the point.

Quote from the linked article (emphasis mine):

> Where convenient, the notation 24:00 may also be used to refer to midnight **at the end** of a given date – that is, 24:00 of one day is the same time as 00:00 of **the following day**.

In the chart, 24:00 is instead used as the **start** of the day. **On the same date**, 24:00 comes before 12:00 – that makes no sense. At the left arrow in the screenshot, either the time has to be 00:00, or, if you insist on using the 24:00 notation, the date has to be 07/03/15.

**Comment by fjyaniez** [comment]
I understand it, this is Google Charts default behaviour but we'll replace Google Charts with Highcharts in the near future.
