### ISSUE TITLE
Erroneous failure report when using both ipv4 and ipv6

### ISSUE THREAD

**Issue by mkyed** [fjyaniez/PortMonitor#13]
I have a monitor on a hostname, which resolves to adresses of both kinds, but it seems that your resolver switches between the A record and the AAAA record when looking it up.
As far as I can see, I can only enter one IP address to compare with (I have entered the IPv4).

So frequently I get failure reports like this:
![2016-09-22 at 09 48](https://cloud.githubusercontent.com/assets/445152/18740444/0b68e692-80aa-11e6-9a59-84df2748763b.png)

**Comment by fjyaniez** [comment]
Ups, thanks for the feedback we'll look into it.

**Comment by mkyed** [comment]
Cool, thanx 😄
