### ISSUE TITLE
Website check failing with internal_error

### ISSUE THREAD

**Issue by Shebuka** [fjyaniez/PortMonitor#15]
I've created a new check to my site at https://www.shebuka.altervista.org/ but it constantly failing with `Received fatal alert: internal_error`.

Maybe it will help you find the problem: the site is backed up by CloudFront and they are providing SSL certificate for the secure connection.

**Comment by fjyaniez** [comment]
Hi Anton,

We have a known problem regarding some SSL setups and Port Monitor not being able to connect to them, I'm afraid this is what's happening to you.

More information: https://github.com/fjyaniez/PortMonitor/issues/9 <https://github.com/fjyaniez/PortMonitor/issues/9>

Could you please in the mean time setup a TCP monitor to port 443 instead a Website monitor?

Best regards,

**Comment by Shebuka** [comment]
This error seems a bit more ugly that one in linked issue.

p.s. TCP monitor to port 443 is working as expected.

**Comment by fjyaniez** [comment]
Hi, we changed the underlying ruby engine and everything should be working fine now.
