### ISSUE TITLE
Lets-encrypt sites

### ISSUE THREAD

**Issue by salorob** [fjyaniez/PortMonitor#16]
Hi there,

i have a few sites using lets-encrypt certificates. 
Could it be those are not supported by Port-Monitor?

e.g. https://www.modulio.nl ?

Wil turn up as failing, where other sites won't.

Regards,

**Comment by fjyaniez** [comment]
Hi,

We have a known problem regarding some SSL setups and Port Monitor not being able to connect to them, I'm afraid this is what's happening to you.

More information: https://github.com/fjyaniez/PortMonitor/issues/9 <https://github.com/fjyaniez/PortMonitor/issues/9>

Could you please in the mean time setup a TCP monitor to port 443 instead a Website monitor?

Best regards,

**Comment by salorob** [comment]
Well, that’s not an option here as the server works on hostnames based on SNI.


Van: Francis Yáñez [mailto:notifications@github.com]
Verzonden: maandag 6 november 2017 17:03
Aan: fjyaniez/PortMonitor <PortMonitor@noreply.github.com>
CC: Robert Salomons <r.salomons@ropesolutions.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [fjyaniez/PortMonitor] Lets-encrypt sites (#16)


Hi,

We have a known problem regarding some SSL setups and Port Monitor not being able to connect to them, I'm afraid this is what's happening to you.

More information: #9<https://github.com/fjyaniez/PortMonitor/issues/9> #9<https://github.com/fjyaniez/PortMonitor/issues/9>

Could you please in the mean time setup a TCP monitor to port 443 instead a Website monitor?

Best regards,

**Comment by fjyaniez** [comment]
Hi, we changed the underlying ruby engine and everything should be working fine now.
