### ISSUE TITLE
Uppercase URL character are saved lowercase

### ISSUE THREAD

**Issue by mrossier** [fjyaniez/PortMonitor#2]
# In the URL field of a target. 

Example: SNAPSHOT becomes snapshot.
# Consequence

The url is not working anymore and the target fails. It is annoying because I can not use the tool for most of my alerts.

**Comment by fjyaniez** [comment]
Hi,

I'll take a look on this one.

**Comment by fjyaniez** [comment]
It's fixed in the current version.

Thanks for your feedback @mrossier

**Comment by mrossier** [comment]
Hi,

I am sorry but it seems the problem is not totally fixed:

1- I create a target like http://www.site.com/SNAPSHOT and save
2- The target column shows http://www.site.com/SNAPSHOT
3- I refresh the page
4- Target column shows http://www.site.com/snapshot

NOTE: the first ping seems to work as there is a recorded response time. Next pings fail.

Thanks

**Comment by fjyaniez** [comment]
I forgot to restart the background daemon.
​
Could you try again? Sorry for the inconveniences.

**Comment by mrossier** [comment]
No problem ! It looks fine now. Thanks

By the way, I like the tool and the GUI, it s clean and simple. It's efficient.

**Comment by fjyaniez** [comment]
Thank you, a simple and clean GUI is our main goal :)
