### ISSUE TITLE
Force HTTPS on homepage.

### ISSUE THREAD

**Issue by basiljelly** [fjyaniez/PortMonitor#3]
Greetings,

I noticed the homepage is only HTTP. When I login I get redirected to HTTPS. Is there a specific reason for this? I was curious if maybe the password box was being sent over HTTPS but it's not. I did a tcpdump on my interface when I logged in and I was able to see my email/password in clear text. 

Here's the actual dump for your reference:

Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Origin: http://www.port-monitor.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Referer: http://www.port-monitor.com/
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8
Cookie: _port-monitor_session=BAh7CEkiCmZsYXNoBjoGRUZvOiVBY3Rpb25EaXNwYXRjaDo
6Rmxhc2g6OkZsYXNoSGFzaAk6CkB1c2VkbzoIU2V0BjoKQGhhc2h7BjoLbm90a
WNlVDoMQGAddedandremovedVNpZ25lZCBvdXsomestufffromLgY7AFQ6CUBub
3cwSSIPc2Vzc2lvbl9pZAY7AEZJIiU4MzmycookiewOWIzMjgzZTY5OTg0NzhkZD
FjNwY7AFRJIhBfY3NyZl90b2tlbgY7AEZJIjFOR3lnUWVkcWRWRGVOYmp2Wjll
WVZmNFZzVm1JWXVaSVpZai9KZFlYNVpzPQY7AEY%3D--dcae3f42d046d9110aca5625f91ec3cff4219216; 

utf8=%E2%9C%93&authenticity_token=NGygQedqdVKJSD9999YVf4VsV2FKjk23JdYSjdjdss%3D&user%5Bemail%5D=myemailwashere&user%5Bpassword%5D=mypasswordwashere&commit=Login

**Comment by fjyaniez** [comment]
Thank you for notifiying this problem @fechterjm, it's fixed now.
