### ISSUE TITLE
"Next check" timestamp in emails has wrong time zone

### ISSUE THREAD

**Issue by hho** [fjyaniez/PortMonitor#4]
In notification emails, the "Next check" timestamp doesn't seem to account for time zones. Because of this, a notification email looks like this:

**Last check:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;18 Jul 18:09:52

**Next check:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;18 Jul 16:10:52

Timezone in my profile is set to GMT+1, and currently europe is on daylight savings time, so that's probably why the difference is two hours. The first timestamp is correctly displayed, the second one seems to be shown in UTC.

**Comment by fjyaniez** [comment]
Thank you for notifying, I'll look into it.

**Comment by fjyaniez** [comment]
It's fixed now.
