### ISSUE TITLE
Force check of website

### ISSUE THREAD

**Issue by iggyvolz** [fjyaniez/PortMonitor#5]
I had Port Monitor set to check my website every 60 seconds (default).   I was doing scheduled maintenance, so I changed it to check every 2147483647 seconds (the maximum) so that the uptime statistics would not be affected.  Now that the scheduled maintenance is over, I changed it back to 60 seconds.  However, it says the next check occurs in 2 weeks.  How can I reset this so that it checks every 60 seconds?

**Comment by fjyaniez** [comment]
Hi, this is clearly a Port Monitor's bug. I'll check into it ASAP.

**Comment by fjyaniez** [comment]
Ok now you can force a check editing the target, in the "Advanced options" tab.

**Comment by iggyvolz** [comment]
That works perfectly, thank you!
