### ISSUE TITLE
editing advanced monitor setting does not work on latest google chrome

### ISSUE THREAD

**Issue by fkierzek** [fjyaniez/PortMonitor#6]

**Comment by fjyaniez** [comment]
Hi,

Could you describe the problem you have found?

**Comment by fkierzek** [comment]
Using google chrome, when I click this:
[image: Inline image 1]
I get this:

[image: Inline image 2]
Which is incorrect - I should get the editing screen. I switched to Firefox
and it works.

Hope this helps.

**Comment by fjyaniez** [comment]
Hi fkierzek,

I have not been able to see your captures. I have tried editing the advanced settings using:
- Latest Chrome for OS X (29.0.1547.76).
- Latest Chrome on Windows 7 (29.0.1547.76 m).

Without problem in both cases.

**Comment by fkierzek** [comment]
Francis - let me know you email adres and I'll send you some screenshots.
My GC version is 30.0.1599.66 beta-m

pozdrawiam

Filip Kierzek
Filip.Kierzek@Gmail.com
T: + 48502304434 | skype: fkierzek

**Comment by fjyaniez** [comment]
@fkierzek detected the problem appeared while using Adblock extension. I fixed the Javascript so it will not fail when Twitter SDK can not be loaded.
