### ISSUE TITLE
Button glitch and typo

### ISSUE THREAD

**Issue by P110** [fjyaniez/PortMonitor#7]
When viewing a group next to the pie chart there are three buttons Events, Response time reports and Uptime time reports.
Uptime time reports may be uptime reports (why time twice?) also, when clicking the uptime button you get taken to the response time report, so maybe the href is pointing the wrong place. So yeah, just a small bug and typo

**Comment by fjyaniez** [comment]
Thanks for notifying, I'll fix this.

**Comment by P110** [comment]
Um.. Just checking in, has this been fixed? If so.. It hasn't been for me... Sorry if I'm being annoying

**Comment by fjyaniez** [comment]
Sorry, it has been fixed but not released. We are doing some big refactoring and testing and it should be deployed soon. Sorry for the inconvenience!—
Francis Yáñez

**Comment by P110** [comment]
Ah, ok, no inconvenience I just wondered what was going on with it

**Comment by fjyaniez** [comment]
I'll close this issue as soon it's released.

**Comment by P110** [comment]
Ok, thanks fjyaniez.
