### ISSUE TITLE
Error: Could not generate DH keypair

### ISSUE THREAD

**Issue by bgraw3** [fjyaniez/PortMonitor#9]
After upgrading some TLS/SSL setting on our server, we are getting a Failure with "Could not generate DH keypair." Google says it's related to Java, etc.

**Comment by fjyaniez** [comment]
I'll need some more info. What's your server hostname?

**Comment by bgraw3** [comment]
Thanks for the quick response.

https://calltrackingmetrics.com/

**Comment by fjyaniez** [comment]
I need to take a deeper look at this, indeed it seems to be Java related. Could you in the meantime change the monitor type to Custom Port and set the port to 443?

**Comment by bgraw3** [comment]
Sorry for the delay. I've made the change. As expected, it's green, now. Let me know if you need anything else and/or when I can change it back. :-)

**Comment by bgraw3** [comment]
Hi. Any updates? We had an outage that was not "seen" because port 443 was still there. I need to be able to check the website, again.
Thanks!

**Comment by fjyaniez** [comment]
Hi, we are waiting for a solid update on this:

https://github.com/jruby/jruby/issues/2220

**Comment by olsio** [comment]
Having the same issue after upgrading the DH input to 4096bit. From what I could see it requires a JVM upgrade.

**Comment by fjyaniez** [comment]
We're using #jruby, waiting for some issues to be resolved... 

https://github.com/jruby/jruby/issues/1774
https://github.com/jruby/jruby/issues/1738

**Comment by ottonet** [comment]
Any news on this issue? Seeing the same with my sites after converting to SSL with a letsencrypt certificate, making port monitor virtually unusable.

**Comment by fjyaniez** [comment]
I'm afraid I don't have any news. Please track this one:

https://github.com/jruby/jruby/issues/1738

The workaround right now is to use a TCP monitor in the 443 port, just to check connectivity. I know it's not the best solution, but it's the only thing we can offer right now.

Regards,

**Comment by fjyaniez** [comment]
We upgraded some libraries, please check your sites again with Port Monitor and let me know the ones still failing.

**Comment by ottonet** [comment]
I can confirm it works a bit better now, but those sites with A+ SSL rating are still failing. I think this is because the JVM you guys use does not support DH parameters > 1024 bits. 

Failing: [livingsmarter.nl](https://livingsmarter.nl), this site has custom DH Parameters with 2048 bits: [SSL Labs A+ rating](https://www.ssllabs.com/ssltest/analyze.html?d=livingsmarter.nl&hideResults=on)

Ok now: [ottonet.nl](https://ottonet.nl), no custom DH Parameters (<= 1024 bits): [SSL Labs A rating](https://www.ssllabs.com/ssltest/analyze.html?d=ottonet.nl&hideResults=on)

**Comment by mdriess** [comment]
Experiencing this issue as well.

**Comment by letailli** [comment]
Hi
We are experiencing the same issue.

What is strange is that we get the error on :
- https://www.6tzen.org/contextChoice
- and https://www.contrat-prive.com/fr/index

But not with those 3 (whereas the ssl settings are similar) :
- https://sve.ordre.medecin.fr/loc_fr/default/
- https://agriculture-portail.6tzen.fr/loc_fr/default/
- https://ceres-portail.6tzen.fr/loc_fr/default

**Comment by Diffusio-agency** [comment]
We currently have 11 websites with HTTPS protocols and only 1 of them has this issue. Any development on this yet?

**Comment by fjyaniez** [comment]
Hi, we changed the underlying ruby engine and everything should be working fine now.
